#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)
clear
echo ${bold}"Updating Development Environment:"${normal}
echo
echo
echo ${bold}"Updating git repos..."${normal}
cd /home/wnovak/git
for REPO in `ls`; do (cd "$REPO"; echo "updating" "$REPO"; git pull; echo ); done
cd /home/wnovak/Scripts/uptater; git pull
echo
wait
echo ${bold}"Updating svn repos..."${normal}
cd /home/wnovak/puppet; svn up & wait
echo
wait
echo ${bold}"Updating System..."${normal}
sudo apt-get update;sudo apt-get upgrade -y
echo
echo ${bold}"--| Complete |--"${normal}
