#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)
clear
echo ${bold}"Updating Development Environment:"${normal}
echo
alias uptate="sh /Users/wnovak/Documents/Scripts/git/uptater/uptater"
echo
echo ${bold}"Updating Homebrew..."${normal}
brew update;brew upgrade & wait
echo
echo ${bold}"Updating oh-my-zsh..."${normal}
sh $ZSH/tools/upgrade.sh
echo
echo ${bold}"Updating git repos..."${normal}
cd /Users/wnovak/Documents/git
for REPO in `ls`; do (cd "$REPO"; echo "updating" "$REPO"; git pull; echo ); done;
cd /Users/wnovak/Documents/Scripts/git/uptater; echo "updating uptater"; git pull & wait
echo
echo ${bold}"Updating svn repos..."${normal}
cd /Users/wnovak/Documents/puppet; svn up & wait
echo
echo ${bold}"OSX Update..."${normal}
softwareupdate -i -a & wait
echo
echo ${bold}"Complete"${normal}
